driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      cachier: true
      customize:
        memory: 1024
        cpus: 2
      network:
        - ["forwarded_port", { guest: 80, host: 8080 }]
        - ["private_network", { ip: "192.168.33.33" }]
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[gamegos-supervisor::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: { foo: "bar" }
